### ISSUE TITLE
make master branch compatible with koa@1 

### ISSUE THREAD

**Issue by dead-horse** [koajs/rewrite#10]
https://github.com/koajs/koa/issues/603

**Comment by tejasmanohar** [comment]
done so, but I need access to NPM for this module (only have github access rn) in order to add the dist-tag `next` for koa-rewrite@2.0.0 @dead-horse @jonathanong

**Comment by dead-horse** [comment]
what's your npm user name ?

**Comment by tejasmanohar** [comment]
tejasmanohar @dead-horse

**Comment by dead-horse** [comment]
added
