### ISSUE TITLE
How to use this

### ISSUE THREAD

**Issue by docikaci** [koajs/rewrite#14]
![image](https://cloud.githubusercontent.com/assets/7788102/18246382/e4275e56-739d-11e6-83b9-ff731e2fe648.png)

How to use this？No effect！！

**Comment by coderhaoxin** [comment]
According to DEBUG msgs, it just works.
What's your intention to use `koa-rewrite`?

**Comment by docikaci** [comment]
@coderhaoxin 
中文：
我想把所有 /api/xxxx的请求，全部重写到/dev_api/xxx  然后在web访问日志里可以看出来重写日志，类似上图debugging描述的那样？

英文：
/api/xxxx   ->rewrite    /dev_api/xxxx


You can look the log

**Comment by coderhaoxin** [comment]
@docikaci 

I think you want to `redirect` `/api/xxxx` to `/dev_api/xxxx`, not path rewrite. :)
