### ISSUE TITLE
support rewrite to headers && query

### ISSUE THREAD

**Issue by atian25** [koajs/rewrite#5]

**Comment by tejasmanohar** [comment]
hm, so this middleware was originally intended for URL rewrite... would like to hear from others on thoughts on header rewrites? guessing that should be in a separate middleware?

**Comment by tj** [comment]
separate IMO

**Comment by 75lb** [comment]
i need to rewrite to querystring: `/one/:two` to `/one?two=:two`.. happy to contribute if you need that feature..

**Comment by coderhaoxin** [comment]
If only for querystring. #8
