### ISSUE TITLE
support rewrite for qs

### ISSUE THREAD

**Issue by coderhaoxin** [koajs/rewrite#8]
Is it acceptable to support rewrite from `qs`?

Such as

```
/items?id=1
```

to

```
/items/1
```

If so, I'll submit a PR.

**Comment by tejasmanohar** [comment]
Yep, sounds fair to me but would be good to hear +/-1 from other users of the module.

**Comment by coderhaoxin** [comment]
https://github.com/koajs/rewrite/pull/13
